language: python
python:
  - "3.6"
before_install:
  - export DJANGO_SETTINGS_MODULE=gymkhana.settings.prod
  - export DJANGO_SECRET_KEY='q$o5mx19x9(9_^rzqf@o@s^t%t!ghix7($f9ymy49_^ryzq9x9'
  - psql -c "CREATE DATABASE gymkhanadb;" -U postgres
install:
  - pip3 install -r requirements/dev.txt
  - pip3 install coveralls
script:
  - cd src
  - flake8 .
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - coverage run manage.py test
#after_success:
#  - coveralls