name: Tests

on: [push, pull_request]

env:
  DJANGO_SETTINGS_MODULE: gymkhana.settings
  DJANGO_SECRET_KEY: "q$o5mx19x9(9_^rzqf@o@s^t%t!ghix7($f9ymy49_^ryzq9x9"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: gymkhanauser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: gymkhanadb
        ports:
        # will assign a random free host port
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Setup environment variables
      run: |
        cp .env.example .env
    - name: Install dependencies
      run: |
        sudo apt-get install libpq-dev 
        pip3 install coveralls
        pip3 install pipenv
        pipenv install --dev
    - name: Linting
      working-directory: ./src
      run: |
        source "$(pipenv --venv)"/bin/activate
        flake8 .
    - name: Migrations
      working-directory: ./src
      run: |
        source "$(pipenv --venv)"/bin/activate
        python3 manage.py makemigrations
        python3 manage.py migrate
    - name: Coverage
      working-directory: ./src
      run: |
        source "$(pipenv --venv)"/bin/activate
        pip3 install coverage
        coverage run --source='.' manage.py test
